# Generated by Django 3.1.1 on 2020-09-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200914_1326'),
        ('faq', '0002_auto_20200925_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
